server:
  port: 8080
  servlet:
    context-path: /carrental

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CarRental;encrypt=true;trustServerCertificate=true
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  thymeleaf:
    cache: false
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.SQLServerDialect

vnpay:
  tmnCode: "XDCKXC4A"
  secretKey: "B1CEZQLM1OETVH5DXHOLDL4G1GC4QZX7"
  payUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl: "http://localhost:8080/carrental/api/payment/vnpay-return"
  ipnUrl: "http://localhost:8080/carrental/api/payment/vnpay-ipn"
