server:
  port: 8080
  servlet:
    context-path: /carrental

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CarRental;encrypt=true;trustServerCertificate=true
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  thymeleaf:
    cache: false   # dev: tắt cache để reload template ngay
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create-drop   # dev thôi; prod nên dùng 'validate' hoặc bỏ hẳn
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.SQLServerDialect

#logging:
#  level:
#    org.thymeleaf: DEBUG
#    org.hibernate.SQL: DEBUG            # in câu SQL
#    org.hibernate.orm.jdbc.bind: TRACE  # in tham số bind của SQL
#    org.springframework.web: INFO
